export const data = [
    {
        "bitWidth": -1, "childrenNum": 1, "displayName": "函数", "displayType": "function", "id": "1", "isActiveUnionMember": false, "isDataNode": false, "isEnumConstant": false, "isEnumNode": false, "isExpanded": true, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "", "realName": "", "realType": "", "value": "----", "valueEditable": false,
        children: [
            {
                "bitWidth": -1, "childrenNum": 2, "displayName": "参数值", "displayType": "", "id": "1.0", "isActiveUnionMember": false, "isDataNode": false, "isEnumConstant": false, "isEnumNode": false, "isExpanded": true, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1", "realName": "", "realType": "", "value": "", "valueEditable": false,
                children: [
                    {
                        "bitWidth": -1, "childrenNum": 5, "displayName": "a1", "displayType": "struct A ", "id": "1.0.0", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": false, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0", "realName": "a1", "realType": "struct A", "value": "", "valueEditable": false,
                        children: [
                            { "bitWidth": -1, "childrenNum": 0, "displayName": "A_a", "displayType": "int ", "id": "1.0.0.0", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": false, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0", "realName": "a1.A_a", "realType": "int", "value": "0", "valueEditable": true },
                            { "bitWidth": -1, "childrenNum": 0, "displayName": "A_b", "displayType": "int ", "id": "1.0.0.1", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": false, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0", "realName": "a1.A_b", "realType": "int", "value": "0", "valueEditable": true },
                            {
                                "bitWidth": -1, "childrenNum": 1, "displayName": "B_ptr", "displayType": "struct B *", "id": "1.0.0.2", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": false, "isEnumNode": false, "isExpanded": false, "isPointer": true, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0", "realName": "a1.B_ptr", "realType": "*;struct B", "value": "", "valueEditable": false,
                                children: [
                                    {
                                        "bitWidth": -1, "childrenNum": 1, "displayName": "B_ptr[0]", "displayType": "struct B ", "id": "1.0.0.2.0", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": false, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": true, "isUnionMember": false, "pid": "1.0.0.2", "realName": "a1.B_ptr[0]", "realType": "struct B", "value": "", "valueEditable": false,
                                        children: [
                                            {
                                                "bitWidth": -1, "childrenNum": 3, "displayName": "abc", "displayType": "enum geo ", "id": "1.0.0.2.0.0", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": false, "isEnumNode": true, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0", "realName": "a1.B_ptr[0].abc", "realType": "enum geo", "value": "0", "valueEditable": true,
                                                children: [
                                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_read", "displayType": "int ", "id": "1.0.0.2.0.0.0", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_read", "realType": "int", "value": "17", "valueEditable": true },
                                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_write", "displayType": "int ", "id": "1.0.0.2.0.0.1", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_write", "realType": "int", "value": "34", "valueEditable": true },
                                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_verify", "displayType": "int ", "id": "1.0.0.2.0.0.2", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_verify", "realType": "int", "value": "51", "valueEditable": true },
                                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_read", "displayType": "int ", "id": "1.0.0.2.0.0.0", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_read", "realType": "int", "value": "17", "valueEditable": true },
                                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_write", "displayType": "int ", "id": "1.0.0.2.0.0.1", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_write", "realType": "int", "value": "34", "valueEditable": true },
                                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_verify", "displayType": "int ", "id": "1.0.0.2.0.0.2", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_verify", "realType": "int", "value": "51", "valueEditable": true },
                                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_read", "displayType": "int ", "id": "1.0.0.2.0.0.0", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_read", "realType": "int", "value": "17", "valueEditable": true },
                                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_write", "displayType": "int ", "id": "1.0.0.2.0.0.1", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_write", "realType": "int", "value": "34", "valueEditable": true },
                                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_verify", "displayType": "int ", "id": "1.0.0.2.0.0.2", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_verify", "realType": "int", "value": "51", "valueEditable": true },
                                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_read", "displayType": "int ", "id": "1.0.0.2.0.0.0", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_read", "realType": "int", "value": "17", "valueEditable": true },
                                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_write", "displayType": "int ", "id": "1.0.0.2.0.0.1", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_write", "realType": "int", "value": "34", "valueEditable": true },
                                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_verify", "displayType": "int ", "id": "1.0.0.2.0.0.2", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_verify", "realType": "int", "value": "51", "valueEditable": true },
                                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_read", "displayType": "int ", "id": "1.0.0.2.0.0.0", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_read", "realType": "int", "value": "17", "valueEditable": true },
                                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_write", "displayType": "int ", "id": "1.0.0.2.0.0.1", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_write", "realType": "int", "value": "34", "valueEditable": true },
                                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_verify", "displayType": "int ", "id": "1.0.0.2.0.0.2", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_verify", "realType": "int", "value": "51", "valueEditable": true },
                                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_read", "displayType": "int ", "id": "1.0.0.2.0.0.0", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_read", "realType": "int", "value": "17", "valueEditable": true },
                                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_write", "displayType": "int ", "id": "1.0.0.2.0.0.1", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_write", "realType": "int", "value": "34", "valueEditable": true },
                                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_verify", "displayType": "int ", "id": "1.0.0.2.0.0.2", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_verify", "realType": "int", "value": "51", "valueEditable": true },
                                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_read", "displayType": "int ", "id": "1.0.0.2.0.0.0", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_read", "realType": "int", "value": "17", "valueEditable": true },
                                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_write", "displayType": "int ", "id": "1.0.0.2.0.0.1", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_write", "realType": "int", "value": "34", "valueEditable": true },
                                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_verify", "displayType": "int ", "id": "1.0.0.2.0.0.2", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_verify", "realType": "int", "value": "51", "valueEditable": true },
                                                ]
                                            },
                                        ]
                                    },
                                ]
                            },
                            {
                                "bitWidth": -1, "childrenNum": 2, "displayName": "弄啥", "displayType": "<anonymous struct> ", "id": "1.0.0.3", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": false, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0", "realName": "a1", "realType": "<anonymous struct at new2.c:15:5>", "value": "", "valueEditable": false,
                                children: [
                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "c", "displayType": "int ", "id": "1.0.0.3.0", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": false, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.3", "realName": "a1.c", "realType": "int", "value": "0", "valueEditable": true },
                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "d", "displayType": "int ", "id": "1.0.0.3.1", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": false, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.3", "realName": "a1.d", "realType": "int", "value": "0", "valueEditable": true },
                                ]
                            },
                            {
                                "bitWidth": -1, "childrenNum": 2, "displayName": "M", "displayType": "<anonymous union> ", "id": "1.0.0.4", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": false, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0", "realName": "a1.M", "realType": "<anonymous union at new2.c:19:5>", "value": "", "valueEditable": false,
                                children: [
                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "M_a", "displayType": "int ", "id": "1.0.0.4.0", "isActiveUnionMember": true, "isDataNode": true, "isEnumConstant": false, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": true, "pid": "1.0.0.4", "realName": "a1.M.M_a", "realType": "int", "value": "0", "valueEditable": true },
                                    { "bitWidth": -1, "childrenNum": 0, "displayName": "M_b", "displayType": "int ", "id": "1.0.0.4.1", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": false, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": true, "pid": "1.0.0.4", "realName": "a1.M.M_b", "realType": "int", "value": "0", "valueEditable": true },
                                ]
                            },

                        ]
                    },
                    {
                        "bitWidth": -1, "childrenNum": 1, "displayName": "b1", "displayType": "struct B *", "id": "1.0.1", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": false, "isEnumNode": false, "isExpanded": false, "isPointer": true, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0", "realName": "b1", "realType": "*;struct B", "value": "", "valueEditable": false,
                        children: [
                            {
                                "bitWidth": -1, "childrenNum": 1, "displayName": "b1[0]", "displayType": "struct B ", "id": "1.0.1.0", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": false, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": true, "isUnionMember": false, "pid": "1.0.1", "realName": "b1[0]", "realType": "struct B", "value": "", "valueEditable": false,
                                children: [
                                    {
                                        "bitWidth": -1, "childrenNum": 3, "displayName": "abc", "displayType": "enum geo ", "id": "1.0.1.0.0", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": false, "isEnumNode": true, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.1.0", "realName": "b1[0].abc", "realType": "enum geo", "value": "0", "valueEditable": true,
                                        children: [
                                            { "bitWidth": -1, "childrenNum": 0, "displayName": "U_read", "displayType": "int ", "id": "1.0.1.0.0.0", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.1.0.0", "realName": "U_read", "realType": "int", "value": "17", "valueEditable": true },
                                            { "bitWidth": -1, "childrenNum": 0, "displayName": "U_write", "displayType": "int ", "id": "1.0.1.0.0.1", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.1.0.0", "realName": "U_write", "realType": "int", "value": "34", "valueEditable": true },
                                        ]
                                    },

                                ]
                            },

                        ]
                        
                    },
                    { "bitWidth": -1, "childrenNum": 0, "displayName": "c1", "displayType": "int ", "id": "1.0.1.0.0.0", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.1.0.0", "realName": "U_read", "realType": "int", "value": "17", "valueEditable": true },

                ]
            }]
    },
]

export const data2=[
    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_write1", "displayType": "int ", "id": "1.0.0.2.0.0.1", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_write", "realType": "int", "value": "34", "valueEditable": true },
    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_verify2", "displayType": "int ", "id": "1.0.0.2.0.0.2", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_verify", "realType": "int", "value": "51", "valueEditable": true },
    { "bitWidth": -1, "childrenNum": 0, "displayName": "U_read3", "displayType": "int ", "id": "1.0.0.2.0.0.0", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.0.2.0.0", "realName": "U_read", "realType": "int", "value": "17", "valueEditable": true },
]

export const data3 ={ "bitWidth": -1, "childrenNum": 0, "displayName": "U_read", "displayType": "int ", "id": "1.0.1.0.0.0", "isActiveUnionMember": false, "isDataNode": true, "isEnumConstant": true, "isEnumNode": false, "isExpanded": false, "isPointer": false, "isPointerChildren": false, "isUnionMember": false, "pid": "1.0.1.0.0", "realName": "U_read", "realType": "int", "value": "17", "valueEditable": true }